### ISSUE TITLE
Criar uma fã page de divulgação no facebook

### ISSUE THREAD

**Issue by Ladeia** [OPAI/flisol-2016#1]

**Comment by HDeiro** [comment]
Acho que não só a fan page, mas todo material de divulgação poderia (deveria, na verdade) ser discutido nesta issue.

**Comment by Ladeia** [comment]
Acho que aqui seria melhor focar so na fã page, criei outra issue com materias promocionais diversos

**Comment by felipegabrielbr** [comment]
Alguém já criou? Vou criar agora a página.

**Comment by HDeiro** [comment]
Cria aí, Gabriel. 

Manda o link depois.

**Comment by felipegabrielbr** [comment]
https://www.facebook.com/flisol2016/

**Comment by icarojerry** [comment]
Coloca como "Done" esta Issue

**Comment by gildasio** [comment]
Fechada, certo? 

https://www.facebook.com/flisol2016/
