### ISSUE TITLE
Escolher uma plataforma de inscrição de usuários

### ISSUE THREAD

**Issue by Ladeia** [OPAI/flisol-2016#3]

**Comment by HDeiro** [comment]
Acho que google forms é a opção mais rápida.

**Comment by Ladeia** [comment]
pose ser a mais rápida, mas podem ter outras tão rápidas quanto e/ou melhores :-)

**Comment by HDeiro** [comment]
O problema é tempo. Se o evento é dia 16 de Abril, acredito que devemos realizar as inscrições de dia 25 a dia 14 (para imprimir lista e blá, blá, blá).

**Comment by felipegabrielbr** [comment]
Também acho o Google Forms uma boa alternativa.

**Comment by gildasio** [comment]
Novamente, vindo da organização do [PHPeetup](http://phpba.com.br/1-PHPeetup-Salvador-2016/), usamos o [Eventick](http://www.eventick.com.br/1o-phpeetup). Muito show, simples e rápido também.

Bacana que para eventos gratuitos eles são sempre gratuitos. Independente da quantidade de usuários.

**Comment by HDeiro** [comment]
@gjuniioor, obrigado pelas sugestões! Iremos verificar!

**Comment by HDeiro** [comment]
@IcaroJerry e @Ladeia , se liguem nessas plataformas.
