### ISSUE TITLE
Divulgar o evento diariamente na página

### ISSUE THREAD

**Issue by Ladeia** [OPAI/flisol-2016#6]

**Comment by icarojerry** [comment]
Começa essa semana mesmo?

**Comment by HDeiro** [comment]
SIM! Quarta-feira.

**Comment by gildasio** [comment]
Tem como deixar isso programado pelas configurações do facebook? Pq daí já pode fechar essa issue.

**Comment by HDeiro** [comment]
@gjuniioor, cara... Não sei se tem como deixar isso configurado. Todavia, quaisquer alterações relevantes do evento estão sendo postadas lá.

**Comment by gildasio** [comment]
Certo. Então se já é algo que está fazendo, fecha essa issue? Bom que dá para ter uma ideia do que realmente falta fazer e tal.

**Comment by HDeiro** [comment]
@gjuniioor Acho uma boa. Estarei fechando esta issue.
